@url = http://localhost:5000

@base = tasks

@taskId = 79e077c3-08b4-4e7c-82a3-6b186b4bb9b8

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZjliNDAxMi03OGUxLTQzZGMtOTdmZC01YjM4MjIzN2NmOWEiLCJ1bmlxdWVfbmFtZSI6ImFmOWI0MDEyLTc4ZTEtNDNkYy05N2ZkLTViMzgyMjM3Y2Y5YSIsIm5iZiI6MTY5MjUzNTYzMywiZXhwIjoxNjkyNTM2MjMzLCJpc3MiOiJkYXRhQmFsay1pc3N1ZXIiLCJhdWQiOiJkYXRhQmFsay1hdWRpZW5jZSJ9.wA_lrkG1AwayaUTIDksA0HsWoCzYiy3NY5H_GhryxXg

### Query: get all tasks
GET {{url}}/{{base}}
Authorization: Bearer {{accessToken}}


### Query: get a single task
GET {{url}}/{{base}}/{{taskId}}
Authorization: Bearer {{accessToken}}


### Command: Create a single task
POST  {{url}}/{{base}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "ba7c2a3e-e8b1-4f04-9e63-4b6ef9c28871",
  "title": "Task post-1",
  "description": "Description for post-1",
  "dueDate": "2023-09-12T00:00:00",
  "assignee": "c5e1e197-22e2-4b32-8f4d-66e800079f7e"
}


### Command: Update a single task
PUT {{url}}/{{base}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": "ba7c2a3e-e8b1-4f04-9e63-4b6ef9c28871",
  "title": "Task post-2",
  "description": "Description for post-2",
  "dueDate": "2023-09-15T00:00:00",
  "assignee": "d0b3d63e-9f7e-4bc0-aa63-5ffef39f5aa4"
}


### Command: Delete Task
DELETE {{url}}/{{base}}/{{taskId}}
Authorization: Bearer {{accessToken}}