@url = http://localhost:5000

@base = tasks

@taskId = 79e077c3-08b4-4e7c-82a3-6b186b4bb9b8


### Query: get all tasks
GET {{url}}/{{base}}


### Query: get a single task
GET {{url}}/{{base}}/{{taskId}}


### Command: Create a single task
POST  {{url}}/{{base}}
Content-Type: application/json

{
  "id": "ba7c2a3e-e8b1-4f04-9e63-4b6ef9c28871",
  "title": "Task post-1",
  "description": "Description for post-1",
  "dueDate": "2023-09-12T00:00:00",
  "assignee": "c5e1e197-22e2-4b32-8f4d-66e800079f7e"
}


### Command: Update a single task
PUT {{url}}/{{base}}
Content-Type: application/json

{
  "id": "ba7c2a3e-e8b1-4f04-9e63-4b6ef9c28871",
  "title": "Task post-2",
  "description": "Description for post-2",
  "dueDate": "2023-09-15T00:00:00",
  "assignee": "d0b3d63e-9f7e-4bc0-aa63-5ffef39f5aa4"
}


### Command: Delete Task
DELETE {{url}}/{{base}}/{{taskId}}