@url = http://localhost:5000

@base = users

@userId1 = 0ddde007-895e-4509-85e1-6fb6c4d0c3af
@userId2 = 9e2a2fc2-7409-4d6b-95db-bc2f40f3d06f
@userId3 = c5e1e197-22e2-4b32-8f4d-66e800079f7e
@userId4 = d0b3d63e-9f7e-4bc0-aa63-5ffef39f5aa4

### Query
GET {{url}}/{{base}}

### Query 
GET {{url}}/{{base}}/{{userId3}}

### Command
POST {{url}}/{{base}}/sign-up
Content-Type: application/json

{
  "email": "userokj5@databalk.io",
  "username": "user5",
  "password": "secret"
}


### Command
# @name sing_in
POST {{url}}/{{base}}/sing-in
Content-Type: application/json

{
  "email": "userokj5@databalk.io",
  "password": "secret"
}

###
@accessToken = {{sing_in.response.body.$.accessToken}}



### Query
GET {{url}}/{{base}}/jwt

### Query
GET {{url}}/{{base}}/secret
Authorization: Bearer {{accessToken}}